steps:
  - name: gcr.io/k8s-skaffold/pack
    id: cloud-native-build
    entrypoint: pack
    args:
      - build
      - rails7-sqlite3-solid-queue
      - -B
      - heroku/builder:22
  - name: gcr.io/cloud-builders/docker
    id: push-image
    waitFor: ['cloud-native-build']
    entrypoint: bash
    args:
      - -c
      - 'docker tag rails7-sqlite3-solid-queue asia-docker.pkg.dev/${PROJECT_ID}/rails7-sqlite3/solid-queue-app && docker push asia-docker.pkg.dev/${PROJECT_ID}/rails7-sqlite3/solid-queue-app'
  - name: gcr.io/cloud-builders/gcloud
    id: deploy
    waitFor: ['push-image']
    args:
      - alpha
      - run
      - deploy
      - rails-solid-queue
      - --allow-unauthenticated
      - --execution-environment
      - gen2
      - --region
      - asia-northeast1
      - --execution-environment
      - gen2
      - --add-volume
      - name=rails-sqlite3,type=cloud-storage,bucket=${PROJECT_ID}-fuse
      - --add-volume-mount
      - volume=rails-sqlite3,mount-path=/workspace/storage/sqlite3
      - --image
      - 'asia-docker.pkg.dev/${PROJECT_ID}/rails7-sqlite3/solid-queue-app'
  - name: gcr.io/cloud-builders/gcloud
    id: migrate
    waitFor: ['deploy']
    args:
      - alpha
      - run
      - jobs
      - deploy
      - --region
      - asia-northeast1
      - migrate
      - --command
      - migrate
      - --execute-now
      - --image
      - 'asia-docker.pkg.dev/${PROJECT_ID}/rails7-sqlite3/solid-queue-app'
      - --wait

images:
  - 'asia-docker.pkg.dev/${PROJECT_ID}/rails7-sqlite3/solid-queue-app'
