default: &default
  use_skip_locked: false
  dispatchers:
    - polling_interval: 1
      batch_size: 1
  workers:
    - queues: "*"
      threads: 1
      processes: 1
      polling_interval: 2

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
